# Generated by Django 4.2.2 on 2023-07-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField(null=True)),
                ('publishing_date', models.DateTimeField()),
                ('author', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
