# Generated by Django 4.2.2 on 2023-07-03 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0002_remove_copy_quantity_copy_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='copy',
            field=models.ForeignKey(default=2013, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='copies.copy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(default=2013, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
