# Generated by Django 4.2.2 on 2023-07-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_copy_loan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
