# Generated by Django 4.2.2 on 2023-06-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('avaliable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
