# Generated by Django 4.2.2 on 2023-07-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_quantity_book_synopsis'),
        ('copies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copy',
            name='quantity',
        ),
        migrations.AddField(
            model_name='copy',
            name='book',
            field=models.ForeignKey(default=2013, on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book'),
            preserve_default=False,
        ),
    ]
