# Generated by Django 4.2.2 on 2023-07-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0002_copy_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copy',
            name='quantity',
        ),
    ]
